version: 2

sources:
  # Source for customer table
  - name: customer
    database: DBT_LABS
    schema: SF_SCHEMA
    tables:
      - name: cust           # logical name used in dbt
        identifier: CUSTOMER # actual table name in Snowflake

  # Source for product and delivery tables
  - name: prod_del
    database: DBT_LABS
    schema: PROD_SCH
    tables:
      - name: prod
        identifier: PRODUCT
      - name: del
        identifier: DELIVERY_STATUS_FACT
